### PR TITLE
Fix typo in docs for withSystemTempFile

### PR DESCRIPTION
**Pull request by kvelicka**

### CODE REVIEW

**Comment by mrkkrp** [comment]
+1

**Comment by mrkkrp** [comment]
I wonder if this package is maintained, though.

**Comment by kvelicka** [comment]
Doesn't seem to be. However, I'm not sure if I'd want to try and take over the maintenance for this..

**Comment by feuerbach** [comment]
It is maintained at https://github.com/feuerbach/temporary. I plan to go over outstanding PRs this weekend.

**Comment by feuerbach** [comment]
@kvelicka your patch is now merged, thank you

**Pull request closed without merging**
